### PR TITLE
Update doc1.py

### PR DESCRIPTION
**Pull request by ksnarkhede**

### CODE REVIEW

**Review by nehapisal-10 — APPROVED** [review]

**Review by nehapisal-10 — COMMENTED** [review]
check the name once and correct it

**Review by ksnarkhede — COMMENTED** [review]
done

**Review by ksnarkhede — COMMENTED** [review]
done

**Comment by ksnarkhede** [comment]
> check the name once and correct it

bye

**Review by nehapisal-10 — APPROVED** [review]

**Pull request merged**
